### ISSUE TITLE
Feedback for the custom home menu

### ISSUE THREAD

**Issue by vaporvee** [cooolgamer/Custom-Homemenu-3DS#1]
The transparent menus in the custom home menu aren't good with the black/gray text for some custom themes. Miiverse ist still called Miiverse in certain countrys like germany. The home menu settings icon is a bit too big. The black bar goes back to normal some times when you open or close friendcodes or the home menu or everything else where you see this bar. Also the text on this black bar is gray. When you touch the power button on the touch screen it goes back to normal you can reproduce it when you touch over it and swipe away.

**Comment by cooolgamer** [comment]
I see the messages some weeks ago, I now finished the v2 with the fixes (I will release it later).
Thanks for the feedback!
