### ISSUE TITLE
A new discovery(?)

### ISSUE THREAD

**Issue by SuguriSweet** [cooolgamer/Custom-Homemenu-3DS#3]
I've been using [Luma Redshift](https://db.universal-team.net/3ds/luma-10.2.1-with-redshift-and-quick-switchers) (I just call it that) for a while and one feature I really like is the support for patching the home menu. Not only does it save more time in building the .cia with the modified changes, but you can also access the eshop! I just wanna let you know about this build of Luma3DS--it's a good workaround for the eshop update issue thing on US consoles.

**Comment by cooolgamer** [comment]
I will make a version with the patches for this luma version, thanks for telling me :)
Since i'm in vacation, I can't do that now, just wait some weeks!
