### ISSUE TITLE
when talking about the Bclyt Layout and switchbox's issues with saving it in the wiki, showing how to fix it via hxd would be a nice addition.

### ISSUE THREAD

**Issue by samiscool51** [cooolgamer/Custom-Homemenu-3DS#5]
much like the title says, showing common problems and how to fix it via hxd would be excellent to improve the wiki.
i'm a smart guy but even i have my limits.
thb this is the best resource to modding the home menu and adding more information to it will only make it better.

**Comment by cooolgamer** [comment]
I see, but the thing is I didn't did that as I don't really know how to explain clearly and I just think I'm about to confuse even more if I give details how to do it... Explaining isn't that easy, I might try to do this later, the wiki isn't full yet yeah

**Comment by cooolgamer** [comment]
Done (sort of), open a new issue if needed
