### ISSUE TITLE
Home Menu

### ISSUE THREAD

**Issue by LeBazarDeBryan** [cooolgamer/Custom-Homemenu-3DS#6]
Hi, I installed the custom home menu you made! It's great but all the buttons and some other things are renamed as "Just Monika" or "Monika". I have a New 3DS XL (EUR).
I wanted to know if it's normal and if there's a way to change that.

Video using the custom home menu: https://mega.nz/file/RdZRmBCQ#pJ9s7dqKRBsoSmYwH1AuuAph6b2kXiG_fTE7sSz0784
without the custom home menu: https://mega.nz/file/5IxXwBbQ#GXUaMjUUIO-lmqjpX0aDVVobwfzLaVMYAf9a1cV0Tv4

Thanks.

**Comment by cooolgamer** [comment]
Check the date ;)

**Comment by LeBazarDeBryan** [comment]
Oh okay! I was thinking it was Monika from the mod I installed on my PC. Is there any way to turn it back to normal or I need to install the previous version of the custom home menu?

**Comment by cooolgamer** [comment]
Just delete the "message" folder from the romfs folder of the mod

**Comment by LeBazarDeBryan** [comment]
Okay, thanks!
