### ISSUE TITLE
Korean Locale translation problem.

### ISSUE THREAD

**Issue by yoonsangmin** [cooolgamer/Custom-Homemenu-3DS#8]
Hello I am korean and I have used your patch to use theme feature.
I am thankful for your work.

However, I found a translation problem using layout feature. I don't know whether you are still maintaining this project but, I provide translation table.
If it will be fixed, I will be happy. 
https://docs.google.com/spreadsheets/d/1JFWAS-gsL8pbm8CG3Tc4XkIjFki90tM7b9bQaW7SoP4/edit?usp=sharing

I am not good at english but, thanks to read this issue.

**Comment by cooolgamer** [comment]
Thanks! I'm happy to see korean people using it and enjoying the theme feature.
I will gladly take translations from korean people because I used Yandex translate for the whole thing because I don't know Korean at all.
Did you see other translations issues? So We can fix all of them at once.
Thanks!

**Comment by yoonsangmin** [comment]
@cooolgamer Thank you for your comment.

I updated the table. I translated from japanese to korean, becuase korean is simular to japanese and this way is more nature when translate.

I took screenshots using minimum patch, but I checked all using recent release. I found all the translation issues I could find, but there may be others.

Thank you for your interest and dedication.

**Comment by yoonsangmin** [comment]
@cooolgamer Hello.

I edited the file myself after checking the wiki.
Here is my edited [menu_msbt_LZ.bin](https://drive.google.com/file/d/1ci83q_-gWenr84suA6GhuKkq6k-XryTQ/view?usp=sharing).

I translated based on Japanese version of HOME menu and only made changes to the badge and home menu layout features, trying not to touch other parts as much as possible. I adjusted it to match other official translations as closely as possible.

Just for your information, I cannot use the badge feature in korean device, but I found there were existing parts that had already been worked on, so I corrected the inaccuracies in the translation. Also, I probably won't use the home layout feature much, but I wanted the translation to be correct.

If you apply it to the official release after reviewing the file, I would really appreciate it.

**Comment by cooolgamer** [comment]
Thanks you, I'm going to test this right now and release if everything is alright (just check if the text fit as I'm not korean) then I release if everything's alright, still thanks you!

**Comment by cooolgamer** [comment]
Here's the badge feature, tell me if everything's OK so I can release it:

https://github.com/cooolgamer/Custom-Homemenu-3DS/assets/64099608/09f49ebe-68ce-41ec-8990-d8397fc81cac

**Comment by yoonsangmin** [comment]
@cooolgamer Thank you for your test.

I didn't know that I can use badge system
I think translation is correct so far. I shared this translation file on korean community and they will share if there is a problem.

**Comment by cooolgamer** [comment]
Do you have a discord server for the korean community? I don't speak korean but it would be nice to join to talk about homemenu or other stuff

**Comment by yoonsangmin** [comment]
@cooolgamer 
No that is not like discord. It's just similar website like reddit.
If you want to get website url, I can provide but the number of Korean users is small.

**Comment by cooolgamer** [comment]
Getting badges on KOR isn't easy, it requires a NNID and KOR doesn't have this so I patched some apps from JPN firmware to the KOR one, then used Pretendo to create a PNID and then use the badges.
It's really not as easy as themes

**Comment by yoonsangmin** [comment]
@cooolgamer Thank you.

I have a japanese 3ds and patched to korean firm with ctrtransfer, and then I could use the badge system.

I found that there are some blanks. So, I will comment after fixing it.

**Comment by yoonsangmin** [comment]
@cooolgamer, I have fix all blanks and test it.

**Comment by cooolgamer** [comment]
No need to post again, I already saw it, I'll check and release later if it's OK

**Comment by cooolgamer** [comment]
Could you send the file? If it's OK, I'll release it (and credit you ofc)

**Comment by yoonsangmin** [comment]
@cooolgamer Thank you so much.

I updated the file in google drive.
[menu_msbt_LZ.bin](https://drive.google.com/file/d/1ci83q_-gWenr84suA6GhuKkq6k-XryTQ/view?usp=sharing).

**Comment by cooolgamer** [comment]
Looks good, I'm going to release it soon, thanks you again! I'm going to close this issue when it's done

**Comment by cooolgamer** [comment]
All done!
